### ISSUE TITLE
Mention more mitigating factors for privacy

### ISSUE THREAD

**Issue by domenic** [horo-t/explainers#1]
Currently you say

> This API can be used for fingerprinting by checking the availability of each feature. However, the Web Platform Design Principles require that each feature be detectable. And this API itself only introduces one bit of information about the availability of the API itself.

But I think we can make stronger statements as well. Such as:

- But in general these things are feature-detectable anyway, it's just that doing so might be async or require a wasteful HTTP request
- But in general just makes new script types like any other new feature-detectable API, like adding a method to an object or a new global.

Also, I think this level of feature detection isn't what we usually call "fingerprinting", since it doesn't vary between users of "the same" browser. (For some not-very-well-defined idea of "same".)

**Comment by horo-t** [comment]
Thanks!

I [Updated](https://github.com/horo-t/explainers/commit/ec0b462c22ec23117eee2b4c3e3b5abfc04aa736) the Privacy Considerations section.

**Comment by domenic** [comment]
Looks great!
